### ISSUE TITLE
factoriser l'envoi des messages côté serveur

### ISSUE THREAD

**Issue by lefevrehenry** [Henry38/Katarenga#17]
avoir une stucture de contrôle côté serveur qui centralise l'envoi des messages au(x) joueur(s)

toutes les fonctions qui envoient des messages seraient uniformes dans leur comportement. Ca permettrait de gérer ces points pour tout le monde:
1. faire attention: un message ne peut pas être envoyé sur les 2 sockets trivialement. Il faut le copier
2. choisir un send bloquant ou non bloquant pour tout le monde
3. que fait-on si on bloque pas et que le messge n'est pas envoyé ?

**Comment by Mommessc** [comment]
Tu peux en dire plus sur ta pensée ?
Les fonctions sendToPlayer et sendToBoth ne suffisent pas ?

**Comment by lefevrehenry** [comment]
oué si en fait complétement
