### ISSUE TITLE
GameInit to GameStatus

### ISSUE THREAD

**Issue by lefevrehenry** [Henry38/Katarenga#2]
changer `GameInit` par `GameStatus`. On demande le status du jeu au serveur à un instant donné, indépendamment du fait si le client est à l'init ou non

C'est aussi plus pertinent pour le spectateur qui rejoint en cours de route de demander le status qui l'init je pense

**Comment by Mommessc** [comment]
Pas totalement d'accord.
Je suis pour changer l'actuel `AskBoardConfiguration` en `AskGameStatus` mais je pense qu'il est bien de garder un message du style de `GameInit` pour signifier par exemple que les 2 joueurs sont prêts et que la partie peut commencer.

**Comment by Mommessc** [comment]
Fixed in 3e122958935a410bac11cb50f5d2653b696fd4b6
