### ISSUE TITLE
find_package version pour zmq et zmqpp

### ISSUE THREAD

**Issue by lefevrehenry** [Henry38/Katarenga#5]
demander au minimum la version de *zmq* (4.3.2 ?) et *zmqpp* (4.2.0 ?) dans les cmakelists

**Comment by Mommessc** [comment]
Tu peux rappeler si c'est ZMQPP ou ZMQ que tu avais en version 3.2 ?

**Comment by lefevrehenry** [comment]
j'avais la version 3.2 de ZMQPP

**Comment by Mommessc** [comment]
Fixed in af04fef2319bf75a53d37bffc6b78378e40583a1
