### ISSUE TITLE
Joueur noir ou blanc dans les callback serveur

### ISSUE THREAD

**Issue by lefevrehenry** [Henry38/Katarenga#8]
côté serveur il serait je pense grandement appréciable lorsqu'on est dans une callback de savoir systématiquement si le message vient du joueur noir ou du joueur blanc

plusieurs pistes
* interroger un booléen ?
* info intégrée dans le message ?
* ajouter un paramètre en argument de la callback

**Comment by Mommessc** [comment]
L'info du joueur qui a envoyé le message est contenue dans le message

**Comment by lefevrehenry** [comment]
justement je suis vraiment pas fan d'intégrer cette info dans les messages

**Comment by lefevrehenry** [comment]
j'ai l'impression que c'est plus un workaround qu'autre chose. Et puis ça laisse la tentation de détourner cette fonctionnalité à d'autres fins ... Bref je suis pas fan je voudrais virer cette info des messages qui n'en ont pas besoin

**Comment by Mommessc** [comment]
Ça permet de pas dupliquer le code parce que les callbacks seront exactement les mêmes, modulo le joueur concerné.
Ensuite connaitre la provenance d'un message ça peut être bien dans le futur si on regroupe tout dans une seule socket "entrante" côté serveur pour les players + spectateurs ou autre (à voir).

**Comment by lefevrehenry** [comment]
éviter de dupliquer du code je suis 100% pour, mais il y a possiblité de faire mieux j'en suis sûr

Par exemple là si je comprends le main thread quand il crée le message X il remplit le champ *player* de ce message pour que le serveur sache que c'est lui qui a envoyé ce message. 

Déjà je pense que le main thread ne devrait pas avoir à se préocupper de ce genre d'info qui ne le concerne pas. Ca rajoute une gestion côté main thread dont on se passerait bien

Ensuite je me dis que ça laisse libre interprétation sur ce champ *player*. Ca amène une confusion entre client et joueur plateau
* *player* c'est le client qui a envoyé ce message ?
* *player* c'est le joueur plateau qui est concerné dans les infos du message ?

Ca manque de convention et de rigueur et c'est pour moi la porte ouverte aux tricks en tout genre dans le futur consciemment ou inconsciemment

Non je pense qu'on peut trouver une solution uniquement serveur-oriented sans polluer les messages

**Comment by Mommessc** [comment]
Si tu veux une solution server-oriented on peut simplement ajouter l'info de l'origine du message en argument de la callback.

Par contre je ne comprends absolument pas ton interrogation concernant le layer qui envoie le message ou le player du plateau.
Ça veut dire quoi le joueur plateau ?

**Comment by lefevrehenry** [comment]
oué c'était pas clair

Mais en gros dans plusieurs message j'ai vu qu'il y avait un champ *player*, et donc je me suis demandé forcément à quoi il pouvait servir. Je pouvais imaginer différente interprétation de ce champ *player* et donc à partir de ce moment j'ai senti que c'était un peu bancale

Je réfléchis encore mais typiquement oui passer par un argument dans la callback c'est une possiblité
